# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "17fa704a57a5ac567f6a938bfaad9110"
application_url = "https://example.com"
embedded = true
name = "spark_zz"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks] 
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "/webhooks/app/subscriptions_update"

[[webhooks.subscriptions]]
topics = ["app_purchases_one_time/update"]
uri = "/webhooks/app/purchases_one_time_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products,read_translations,write_translations,read_locales,read_content"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
