# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "940b967eda872dd81f9ffc283e29a013"
name = "AiAssistant-Test"
application_url = "https://aiassistant-wi7b.onrender.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products,read_translations,write_translations,read_locales"

[auth]
redirect_urls = [ "https://aiassistant-wi7b.onrender.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
