# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "940b967eda872dd81f9ffc283e29a013"
name = "AiAssistant-Test"
application_url = "https://aiassistant-wi7b.onrender.com"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = ["orders/paid"]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = ["orders/cancelled"]
  uri = "/webhooks/orders/cancelled"

  [[webhooks.subscriptions]]
  topics = ["refunds/create"]
  uri = "/webhooks/refunds/create"

  [[webhooks.subscriptions]]
  topics = ["inventory_levels/update"]
  uri = "/webhooks/inventory_levels/update"

  [[webhooks.subscriptions]]
  topics = ["fulfillments/create"]
  uri = "/webhooks/fulfillments/create"

  [[webhooks.subscriptions]]
  topics = ["fulfillments/update"]
  uri = "/webhooks/fulfillments/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products,read_locales,read_translations,write_translations"

[auth]
redirect_urls = [ "https://aiassistant-wi7b.onrender.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
