# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bbcbe0c2125028b8bf866f2198306c8"
name = "order monitor test zz"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_fulfillments,read_inventory,write_products,read_translations,write_translations,read_locales,read_content,read_products,write_orders"

optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["orders/paid"]
uri = "/webhooks/orders/paid"

[[webhooks.subscriptions]]
topics = ["orders/cancelled"]
uri = "/webhooks/orders/cancelled"

[[webhooks.subscriptions]]
topics = ["refunds/create"]
uri = "/webhooks/refunds/create"

[[webhooks.subscriptions]]
topics = ["fulfillments/create"]
uri = "/webhooks/fulfillments/create"

[[webhooks.subscriptions]]
topics = ["fulfillments/update"]
uri = "/webhooks/fulfillments/update"

[[webhooks.subscriptions]]
topics = ["inventory_levels/update"]
uri = "/webhooks/inventory_levels/update"

[build]
automatically_update_urls_on_dev = true
