client_id = "9679913386b973ae0552744619ccd333"
name = "Desc - Test - ZZ"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "/webhooks/app/subscriptions_update"

[[webhooks.subscriptions]]
topics = ["app_purchases_one_time/update"]
uri = "/webhooks/app/purchases_one_time_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_locales,write_products"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
]

[build]
automatically_update_urls_on_dev = true
