# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dae0dae9cfeca7c8ba3bd0297d2f2e38"
name = "Ciwi:ai-Product Improve"
application_url = "https://product-improve.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,write_products"

[auth]
redirect_urls = [ "https://product-improve.onrender.com/api/auth" ]