-- PlanCatalog 种子（turso:migrate 执行；product-improve 使用 pi_* planKey）
DELETE FROM "PlanCatalog" WHERE "appName" = 'generate-description' OR "planKey" LIKE 'gd_%';

INSERT INTO "PlanCatalog" (
    "planKey",
    "appName",
    "kind",
    "billingInterval",
    "displayName",
    "tokens",
    "priceAmount",
    "currencyCode",
    "trialDays",
    "shopifyPlanName",
    "sortOrder",
    "enabled",
    "createdAt",
    "updatedAt"
) VALUES
    (
        'pi_trial',
        'product-improve',
        'INTERNAL_TRIAL',
        NULL,
        'Free trial',
        10000,
        '0',
        'USD',
        NULL,
        'Product Improve Free Trial',
        10,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'pi_base_monthly',
        'product-improve',
        'SUBSCRIPTION',
        'MONTHLY',
        'Base (Monthly)',
        500000,
        '29.99',
        'USD',
        7,
        'Product Improve Base Monthly',
        20,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'pi_base_annual',
        'product-improve',
        'SUBSCRIPTION',
        'ANNUAL',
        'Base (Annual)',
        6500000,
        '299.99',
        'USD',
        7,
        'Product Improve Base Annual',
        30,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'pi_pro_monthly',
        'product-improve',
        'SUBSCRIPTION',
        'MONTHLY',
        'Pro (Monthly)',
        2000000,
        '79.99',
        'USD',
        7,
        'Product Improve Pro Monthly',
        25,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'pi_pro_annual',
        'product-improve',
        'SUBSCRIPTION',
        'ANNUAL',
        'Pro (Annual)',
        26000000,
        '799.99',
        'USD',
        7,
        'Product Improve Pro Annual',
        35,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'pi_pack_100k',
        'product-improve',
        'ONE_TIME_PACK',
        NULL,
        'Token pack 100K',
        100000,
        '9.99',
        'USD',
        NULL,
        'Product Improve Token Pack 100K',
        40,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'pi_pack_500k',
        'product-improve',
        'ONE_TIME_PACK',
        NULL,
        'Token pack 500K',
        500000,
        '39.99',
        'USD',
        NULL,
        'Product Improve Token Pack 500K',
        50,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'pi_pack_1m',
        'product-improve',
        'ONE_TIME_PACK',
        NULL,
        'Token pack 1M',
        1000000,
        '69.99',
        'USD',
        NULL,
        'Product Improve Token Pack 1M',
        60,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'pi_pack_2m',
        'product-improve',
        'ONE_TIME_PACK',
        NULL,
        'Token pack 2M',
        2000000,
        '129.99',
        'USD',
        NULL,
        'Product Improve Token Pack 2M',
        70,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT("planKey") DO UPDATE SET
    "appName" = excluded."appName",
    "kind" = excluded."kind",
    "billingInterval" = excluded."billingInterval",
    "displayName" = excluded."displayName",
    "tokens" = excluded."tokens",
    "priceAmount" = excluded."priceAmount",
    "currencyCode" = excluded."currencyCode",
    "trialDays" = excluded."trialDays",
    "shopifyPlanName" = excluded."shopifyPlanName",
    "sortOrder" = excluded."sortOrder",
    "enabled" = excluded."enabled",
    "updatedAt" = CURRENT_TIMESTAMP;
