-- PlanCatalog 种子（turso:migrate 执行；spark_* planKey）
DELETE FROM "PlanCatalog" WHERE "planKey" LIKE 'gd_%' OR "planKey" LIKE 'pi_%';

INSERT INTO "PlanCatalog" (
    "planKey",
    "appName",
    "kind",
    "billingInterval",
    "displayName",
    "tokens",
    "priceAmount",
    "currencyCode",
    "shopifyPlanName",
    "overagePricePerThousand",
    "defaultOverageCapAmount",
    "overageTerms",
    "sortOrder",
    "enabled",
    "createdAt",
    "updatedAt"
) VALUES
    (
        'spark_base_monthly',
        'spark',
        'SUBSCRIPTION',
        'MONTHLY',
        'Basic (Monthly)',
        500000,
        '9.99',
        'USD',
        'Spark Basic Monthly',
        '0.025',
        '50.00',
        'Overage tokens beyond plan allowance at $0.025 per 1,000 tokens. Billed up to the capped amount each billing cycle.',
        20,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'spark_base_annual',
        'spark',
        'SUBSCRIPTION',
        'ANNUAL',
        'Basic (Annual)',
        6500000,
        '99.99',
        'USD',
        'Spark Basic Annual',
        '0.025',
        '50.00',
        'Overage tokens beyond plan allowance at $0.025 per 1,000 tokens. Billed up to the capped amount each billing cycle.',
        30,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'spark_pro_monthly',
        'spark',
        'SUBSCRIPTION',
        'MONTHLY',
        'Pro (Monthly)',
        2500000,
        '39.99',
        'USD',
        'Spark Pro Monthly',
        '0.025',
        '100.00',
        'Overage tokens beyond plan allowance at $0.025 per 1,000 tokens. Billed up to the capped amount each billing cycle.',
        25,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'spark_pro_annual',
        'spark',
        'SUBSCRIPTION',
        'ANNUAL',
        'Pro (Annual)',
        32500000,
        '399.99',
        'USD',
        'Spark Pro Annual',
        '0.025',
        '100.00',
        'Overage tokens beyond plan allowance at $0.025 per 1,000 tokens. Billed up to the capped amount each billing cycle.',
        35,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'spark_premium_monthly',
        'spark',
        'SUBSCRIPTION',
        'MONTHLY',
        'Premium (Monthly)',
        10000000,
        '99.99',
        'USD',
        'Spark Premium Monthly',
        '0.025',
        '200.00',
        'Overage tokens beyond plan allowance at $0.025 per 1,000 tokens. Billed up to the capped amount each billing cycle.',
        40,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'spark_premium_annual',
        'spark',
        'SUBSCRIPTION',
        'ANNUAL',
        'Premium (Annual)',
        130000000,
        '999.99',
        'USD',
        'Spark Premium Annual',
        '0.025',
        '200.00',
        'Overage tokens beyond plan allowance at $0.025 per 1,000 tokens. Billed up to the capped amount each billing cycle.',
        45,
        1,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'spark_pack_100k',
        'spark',
        'ONE_TIME_PACK',
        NULL,
        'Token pack 100K',
        100000,
        '9.99',
        'USD',
        'Spark Token Pack 100K',
        NULL,
        NULL,
        NULL,
        50,
        0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'spark_pack_500k',
        'spark',
        'ONE_TIME_PACK',
        NULL,
        'Token pack 500K',
        500000,
        '39.99',
        'USD',
        'Spark Token Pack 500K',
        NULL,
        NULL,
        NULL,
        60,
        0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'spark_pack_1m',
        'spark',
        'ONE_TIME_PACK',
        NULL,
        'Token pack 1M',
        1000000,
        '69.99',
        'USD',
        'Spark Token Pack 1M',
        NULL,
        NULL,
        NULL,
        70,
        0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'spark_pack_2m',
        'spark',
        'ONE_TIME_PACK',
        NULL,
        'Token pack 2M',
        2000000,
        '129.99',
        'USD',
        'Spark Token Pack 2M',
        NULL,
        NULL,
        NULL,
        80,
        0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT("planKey") DO UPDATE SET
    "appName" = excluded."appName",
    "kind" = excluded."kind",
    "billingInterval" = excluded."billingInterval",
    "displayName" = excluded."displayName",
    "tokens" = excluded."tokens",
    "priceAmount" = excluded."priceAmount",
    "currencyCode" = excluded."currencyCode",
    "shopifyPlanName" = excluded."shopifyPlanName",
    "overagePricePerThousand" = excluded."overagePricePerThousand",
    "defaultOverageCapAmount" = excluded."defaultOverageCapAmount",
    "overageTerms" = excluded."overageTerms",
    "sortOrder" = excluded."sortOrder",
    "enabled" = excluded."enabled",
    "updatedAt" = CURRENT_TIMESTAMP;
