import { EMAIL_TEMPLATE_IDS } from "../../../email/templates/emailTemplates.server";

export const SEND_TEMPLATE_EMAIL_TOOL_NAME = "send_template_email";

export const SEND_TEMPLATE_EMAIL_LOG_PREFIX = "[EmailTool]";

/** Agent 可发送的模板 ID（排除纯运营自动化如 FIRST_INSTALL） */
export const AGENT_ALLOWED_TEMPLATE_IDS = [
  EMAIL_TEMPLATE_IDS.TRANSLATION_SUCCESS,
  EMAIL_TEMPLATE_IDS.TRANSLATION_FAILED,
  EMAIL_TEMPLATE_IDS.AUTO_TRANSLATION_SUCCESS,
  EMAIL_TEMPLATE_IDS.CHARACTER_PURCHASE,
  EMAIL_TEMPLATE_IDS.PLAN_TRIAL,
  EMAIL_TEMPLATE_IDS.PLAN_UPGRADE,
  EMAIL_TEMPLATE_IDS.PLAN_UPGRADE_ALT,
  EMAIL_TEMPLATE_IDS.IP_RUNNING_OUT,
  EMAIL_TEMPLATE_IDS.IP_OUT,
  EMAIL_TEMPLATE_IDS.SUBSCRIBE_SUCCESS,
  EMAIL_TEMPLATE_IDS.APG_INIT,
  EMAIL_TEMPLATE_IDS.APG_PURCHASE,
  EMAIL_TEMPLATE_IDS.APG_TASK_INTERRUPT,
  EMAIL_TEMPLATE_IDS.IP_REPORT,
] as const;

export type AgentAllowedTemplateId = (typeof AGENT_ALLOWED_TEMPLATE_IDS)[number];

export function isAgentAllowedTemplateId(templateId: number): templateId is AgentAllowedTemplateId {
  return (AGENT_ALLOWED_TEMPLATE_IDS as readonly number[]).includes(templateId);
}

export const AGENT_EMAIL_ERROR_CODES = {
  INVALID_TEMPLATE_ID: "INVALID_TEMPLATE_ID",
} as const;
