/**
 * v4 定时自动翻译模块（不含 EMAIL_TEMPLATE — 邮件仅支持手动任务）。
 * 权威列表：worker/scripts/v4-auto-translate-modules.json
 * 注：Spring v2 TaskService.AUTO_TRANSLATE_MAP 仍含 EMAIL_TEMPLATE，v4 已刻意排除。
 */
export const AUTO_TRANSLATE_V4_MODULES = [
  "SHOP",
  "MENU",
  "LINK",
  "FILTER",
  "PACKING_SLIP_TEMPLATE",
  "DELIVERY_METHOD_DEFINITION",
  "METAOBJECT",
  "ONLINE_STORE_THEME_JSON_TEMPLATE",
  "ONLINE_STORE_THEME_SECTION_GROUP",
  "ONLINE_STORE_THEME_SETTINGS_CATEGORY",
  "ONLINE_STORE_THEME_SETTINGS_DATA_SECTIONS",
  "COLLECTION",
  "PRODUCT",
  "PRODUCT_OPTION",
  "PRODUCT_OPTION_VALUE",
  "BLOG",
  "ARTICLE",
  "PAGE",
  "METAFIELD",
  "SHOP_POLICY",
  "SELLING_PLAN",
  "SELLING_PLAN_GROUP",
] as const;

/** @deprecated 使用 AUTO_TRANSLATE_V4_MODULES */
export const V2_AUTO_TRANSLATE_MODULES = AUTO_TRANSLATE_V4_MODULES;
