/**
 * v4 自动翻译模块 — 对齐 Java TaskService.AUTO_TRANSLATE_MAP。
 */
export const AUTO_TRANSLATE_V4_MODULES = [
  "SHOP",
  "MENU",
  "LINK",
  "FILTER",
  "PACKING_SLIP_TEMPLATE",
  "DELIVERY_METHOD_DEFINITION",
  "METAOBJECT",
  "ONLINE_STORE_THEME_JSON_TEMPLATE",
  "ONLINE_STORE_THEME_SECTION_GROUP",
  "ONLINE_STORE_THEME_SETTINGS_CATEGORY",
  "ONLINE_STORE_THEME_SETTINGS_DATA_SECTIONS",
  "COLLECTION",
  "PRODUCT",
  "PRODUCT_OPTION",
  "PRODUCT_OPTION_VALUE",
  "BLOG",
  "ARTICLE",
  "PAGE",
  "METAFIELD",
  "SHOP_POLICY",
  "SELLING_PLAN",
  "SELLING_PLAN_GROUP",
] as const;
